### ISSUE TITLE
simple beginner question

### ISSUE THREAD

**Issue by WAINGOR** [welaika/wordless_gem#12]
Hi all, I am trying to setup Wordless. I have installed it with gem, but I get this error:
Cannot login to MySQL. Wrong credentials? I am working on a Mac with macOS Sierra 10.12.16

I thought maybe I have to give a standard password for localhost? So I tried all things below here in terminal but I dont think I am using the correct syntax :(  Any ideas? also how do I start mySQL? I have it running now on MAMP Pro. Is that not enough maybe? 

mbpvanverdel2:lokaalWP o.vanvelsen$ --db-password= root
-bash: --db-password=: command not found
mbpvanverdel2:lokaalWP o.vanvelsen$ wordless --db-password= root
Could not find command "__db_password=".
mbpvanverdel2:lokaalWP o.vanvelsen$ wordless --db-password= 'root'
Could not find command "__db_password=".
mbpvanverdel2:lokaalWP o.vanvelsen$ [--db-password=root] 
-bash: [--db-password=root]: command not found
mbpvanverdel2:lokaalWP o.vanvelsen$

**Comment by pioneerskies** [comment]
Hello there,

I think your command should look almost like

    wordless new your_project_name --db-password=root

Is enough to have mysql started by MAMP, but you have to know the right parameters to connect to it. Reading its documentation, seems all you need could be the command above. Let me know :)

**Comment by WAINGOR** [comment]
Hi Pioneerskies, and thank you so much for helping. I just installed mysql from their website. When I installed it I got this message (please see image) 
I tried to fill in the password they gave me but I still get the same error... Where can I find the right credentials for MySQL? Im very confused

**Comment by pioneerskies** [comment]
Well...I'm sorry, but there are so many different MySQL setups out there, that is impossible to me to give support about theme all.

From what I can see you should be able to connect to your mysql instance using

    mysql -u root -h localhost -pZKg5kLA%N,a1

Do not try over again with the gem, until you can't connect to your mysql using the reported command: the gem will use such command to connect to your mysql and create a new database, and troubleshooting that way you can find an entire universe of more common support about setting up.

The exact complete command the gem is executing before dropping the

    Cannot login to MySQL. Wrong credentials?

is

    mysql --user='db_user' --password='db_password' --execute='QUIT'

Hope this will help you finding a clue

**Comment by WAINGOR** [comment]
It took asking the help of 3 senior developers but we managed to get it to work :P Thanks for taking your time to support!Greets
