### ISSUE TITLE
Undefined problem with 5-minutes installation

### ISSUE THREAD

**Issue by emendelski** [welaika/wordless_gem#13]
![zrzut ekranu 2018-02-08 o 13 31 25](https://user-images.githubusercontent.com/796237/35973100-73dcb64c-0cd4-11e8-93d2-92af03138937.png)

@pioneerskies - Is there any chance to diagnose or debug what have happened?

**Comment by pioneerskies** [comment]
Hello @emendelski ,

this little cli-tool hasn't a polished debugging interface. I can tell you that the failing command is

```ruby
"wp core install --url='#{options[:site_url]}' --title='#{dir_name}' --admin_user='#{options[:admin_user]}' --admin_password='#{options[:admin_password]}' --admin_email='#{options[:admin_email]}'"
```

Would you mind to correctly populate the flag and try to invoke it directly within your project root?

**Comment by pioneerskies** [comment]
Just as technical ref. the code is in welaika/wordpress_tools gem and specifically @ https://github.com/welaika/wordpress_tools/blob/ff5586dd99a453e4af3a1b2a86f3fa9895f2bbc2/lib/wordpress_tools/wordpress.rb#L86
