### ISSUE TITLE
Node isn't installed error

### ISSUE THREAD

**Issue by vincentntang** [welaika/wordless_gem#14]
Not sure why I'm getting this error

![image](https://user-images.githubusercontent.com/10290348/42719994-7f068d5c-86ed-11e8-8c78-a9a1089208a1.png)

I checked `node -v` and `npm -v` and it says I have node / npm installed. Might it not work on newer versions of node / npm?

**Comment by JackPoteYes** [comment]
Same here, please follow

**Comment by pioneerskies** [comment]
I'm back to school. I can't test the gem on windows, but I'll check the code in search of some windows incompatibility I can recognize.

**Comment by pioneerskies** [comment]
Here https://github.com/welaika/wordless_gem/blob/master/lib/wordless/wordless_cli.rb#L65 we use a *nix only existence check. We should brutally copy/paste from SO https://stackoverflow.com/a/5471032/1275834 😝 

I'll schedule this one quite soon :)

Thanks for sharing the issue

**Comment by pioneerskies** [comment]
Autoclosed by commit, but I'd like to have your feedbacks anyway - if you mind

**Comment by pioneerskies** [comment]
@vincentntang @JackPoteYes any feedback?
