### ISSUE TITLE
wordless clean does not clean all static assets

### ISSUE THREAD

**Issue by endorama** [welaika/wordless_gem#7]
Hello, I've found a strange behaviour in `wordless clean`.

`wordless compile` produces 4 assets, but `wordless clean` deletes only 2 of them. Any hint on why this is happening?

```
$ wordless compile
  wp-content/themes/techlab/assets/javascripts/application.js
  wp-content/themes/techlab/assets/javascripts/home.js
  wp-content/themes/techlab/assets/javascripts/svg-inliner.js
  wp-content/themes/techlab/assets/stylesheets/screen.css
$ wordless clean
$ ls wp-content/themes/techlab/assets
  wp-content/themes/techlab/assets/javascripts/home.js
  wp-content/themes/techlab/assets/javascripts/svg-inliner.js
```

wordless version 0.4.1

**Comment by pioneerskies** [comment]
Hi @endorama :)

I think the gem assumes just the wordless default static assets exist by default: `application.js` and `screen.css`. In order to correctly clean your custom files try to put something like this in your `Wordfile`:

```yaml
static_js:
  - wp-content/themes/techlab/assets/javascripts/home.js
  - wp-content/themes/techlab/assets/javascripts/svg-inliner.js
```

Let me know if it works

**Comment by endorama** [comment]
You're right! :) Thanks for helping
